Polarization file from LOBSTER.
Units are  μC/cm2

         Rel. Mulliken pol. vector       Rel. Loewdin pol. vector
  x                           0.47                           0.47
  y                           4.64                           3.72
  z                          -1.01                          -0.75
abs                           4.77                           3.83
                    unit:  μC/cm2                 unit:  μC/cm2
