Polarization file from LOBSTER.
Units are  μC/cm2

         Rel. Mulliken pol. vector       Rel. Loewdin pol. vector
  x                           1.51                           1.30
  y                           4.08                           3.36
  z                          -1.00                          -0.75
abs                           4.46                           3.68
                    unit:  μC/cm2                 unit:  μC/cm2
