Polarization file from LOBSTER.
Units are  μC/cm2

         Rel. Mulliken pol. vector       Rel. Loewdin pol. vector
  x                           0.74                           0.70
  y                           4.83                           3.79
  z                          -1.01                          -0.75
abs                           4.99                           3.93
                    unit:  μC/cm2                 unit:  μC/cm2
