Polarization file from LOBSTER.
Units are  μC/cm2

         Rel. Mulliken pol. vector       Rel. Loewdin pol. vector
  x                           0.58                           0.60
  y                           2.11                           1.56
  z                          -1.11                          -0.84
abs                           2.46                           1.87
                    unit:  μC/cm2                 unit:  μC/cm2
