Polarization file from LOBSTER.
Units are  μC/cm2

         Rel. Mulliken pol. vector       Rel. Loewdin pol. vector
  x                           0.71                           0.69
  y                           4.05                           3.22
  z                          -0.97                          -0.72
abs                           4.22                           3.37
                    unit:  μC/cm2                 unit:  μC/cm2
