Polarization file from LOBSTER.
Units are  μC/cm2

         Rel. Mulliken pol. vector       Rel. Loewdin pol. vector
  x                           0.35                           0.35
  y                           4.68                           3.67
  z                          -0.98                          -0.73
abs                           4.79                           3.76
                    unit:  μC/cm2                 unit:  μC/cm2
